version: '3.8'

services:
  events:
    build:
      context: .
      dockerfile: Dockerfile
    image: events
    container_name: events
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SWAGGER_PASS: ${SWAGGER_PASS}
      ID_ROLE_SUPERADMIN: ${ID_ROLE_SUPERADMIN}
      ID_ROLE_SUBSCRIBER: ${ID_ROLE_SUBSCRIBER}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      REDIS: ${REDIS}
      PORT_REDIS: ${PORT_REDIS}
networks:
  events:
